services:
  # Main service
  kaia-agent-research:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kaia-agent-research
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    env_file:
      - .env
    environment:
      - TZ=UTC
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - PUPPETEER_ARGS=--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-gpu,--headless=new,--no-first-run,--no-zygote
      - DEFAULT_NAVIGATION_TIMEOUT=120000
      - DEFAULT_TIMEOUT=90000
    command: >
      sh -c "
        mkdir -p /app/data &&
        if [ ! -f /app/data/delphi_cookies.json ]; then echo '{}' > /app/data/delphi_cookies.json; fi &&
        npm run delphi:run"